/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AgroInnove;

import java.awt.Color;

/**
 *
 * @author azael
 */
public class Nuevo_Usuario extends javax.swing.JFrame {

    int xMouse, yMouse;
    Color verde = new Color(72, 110, 1);
    public Nuevo_Usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_FondoAb = new javax.swing.JPanel();
        Pnl_Barra = new javax.swing.JPanel();
        Panel_Fondo = new javax.swing.JPanel();
        lbl_INICIOS = new javax.swing.JLabel();
        lbl_Contraseña = new javax.swing.JLabel();
        lbl_Usuario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txt_Usuario = new javax.swing.JTextField();
        txt_contraseña = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        txt_contraseñaRectificar = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        lbl_Contraseña1 = new javax.swing.JLabel();
        btn_Atras = new javax.swing.JPanel();
        lbl_Atras = new javax.swing.JLabel();
        btn_Registrar = new javax.swing.JPanel();
        lbl_Registrar = new javax.swing.JLabel();
        txt_Correo = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lbl_Usuario1 = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        lbl_Usuario2 = new javax.swing.JLabel();
        lbl_Usuario3 = new javax.swing.JLabel();
        txt_Apellidos = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        txt_Telefono = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        lbl_Usuario4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        pnl_FondoAb.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pnl_Barra.setBackground(new java.awt.Color(153, 153, 153));
        Pnl_Barra.setForeground(new java.awt.Color(102, 102, 102));
        Pnl_Barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Pnl_BarraMouseDragged(evt);
            }
        });
        Pnl_Barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Pnl_BarraMousePressed(evt);
            }
        });

        javax.swing.GroupLayout Pnl_BarraLayout = new javax.swing.GroupLayout(Pnl_Barra);
        Pnl_Barra.setLayout(Pnl_BarraLayout);
        Pnl_BarraLayout.setHorizontalGroup(
            Pnl_BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        Pnl_BarraLayout.setVerticalGroup(
            Pnl_BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        pnl_FondoAb.add(Pnl_Barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 30));

        Panel_Fondo.setBackground(new java.awt.Color(255, 255, 255));

        lbl_INICIOS.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        lbl_INICIOS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_INICIOS.setText("Nuevo usuario");

        lbl_Contraseña.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbl_Contraseña.setText("Contraseña");

        lbl_Usuario.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbl_Usuario.setText("Usuario (Dentro de la aplicación)");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        txt_Usuario.setBackground(new java.awt.Color(204, 204, 204));
        txt_Usuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_Usuario.setBorder(null);
        txt_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_UsuarioMousePressed(evt);
            }
        });
        txt_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UsuarioActionPerformed(evt);
            }
        });
        txt_Usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_UsuarioKeyTyped(evt);
            }
        });

        txt_contraseña.setBackground(new java.awt.Color(204, 204, 204));
        txt_contraseña.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_contraseña.setBorder(null);
        txt_contraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_contraseñaMousePressed(evt);
            }
        });
        txt_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contraseñaActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        txt_contraseñaRectificar.setBackground(new java.awt.Color(204, 204, 204));
        txt_contraseñaRectificar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_contraseñaRectificar.setBorder(null);
        txt_contraseñaRectificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_contraseñaRectificarMousePressed(evt);
            }
        });
        txt_contraseñaRectificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contraseñaRectificarActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        lbl_Contraseña1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbl_Contraseña1.setText("Rectifica la contraseña");

        btn_Atras.setBackground(new java.awt.Color(204, 204, 204));
        btn_Atras.setForeground(new java.awt.Color(0, 153, 255));

        lbl_Atras.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbl_Atras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Atras.setText("Atras");
        lbl_Atras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_Atras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_AtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_AtrasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_AtrasMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btn_AtrasLayout = new javax.swing.GroupLayout(btn_Atras);
        btn_Atras.setLayout(btn_AtrasLayout);
        btn_AtrasLayout.setHorizontalGroup(
            btn_AtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_AtrasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btn_AtrasLayout.setVerticalGroup(
            btn_AtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btn_Registrar.setBackground(new java.awt.Color(204, 204, 204));
        btn_Registrar.setForeground(new java.awt.Color(0, 153, 255));

        lbl_Registrar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbl_Registrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Registrar.setText("Registrar");
        lbl_Registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_Registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_RegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_RegistrarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_RegistrarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btn_RegistrarLayout = new javax.swing.GroupLayout(btn_Registrar);
        btn_Registrar.setLayout(btn_RegistrarLayout);
        btn_RegistrarLayout.setHorizontalGroup(
            btn_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_RegistrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btn_RegistrarLayout.setVerticalGroup(
            btn_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_RegistrarLayout.createSequentialGroup()
                .addComponent(lbl_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        txt_Correo.setBackground(new java.awt.Color(204, 204, 204));
        txt_Correo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_Correo.setBorder(null);
        txt_Correo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_CorreoMousePressed(evt);
            }
        });
        txt_Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CorreoActionPerformed(evt);
            }
        });
        txt_Correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_CorreoKeyTyped(evt);
            }
        });

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        lbl_Usuario1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbl_Usuario1.setText("Correo electronico");

        txt_Nombre.setBackground(new java.awt.Color(204, 204, 204));
        txt_Nombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_Nombre.setBorder(null);
        txt_Nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_NombreMousePressed(evt);
            }
        });
        txt_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NombreActionPerformed(evt);
            }
        });
        txt_Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NombreKeyTyped(evt);
            }
        });

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        lbl_Usuario2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbl_Usuario2.setText("Nombre(s)");

        lbl_Usuario3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbl_Usuario3.setText("Apellidos");

        txt_Apellidos.setBackground(new java.awt.Color(204, 204, 204));
        txt_Apellidos.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_Apellidos.setBorder(null);
        txt_Apellidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_ApellidosMousePressed(evt);
            }
        });
        txt_Apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ApellidosActionPerformed(evt);
            }
        });
        txt_Apellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ApellidosKeyTyped(evt);
            }
        });

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));

        txt_Telefono.setBackground(new java.awt.Color(204, 204, 204));
        txt_Telefono.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_Telefono.setBorder(null);
        txt_Telefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_TelefonoMousePressed(evt);
            }
        });
        txt_Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TelefonoActionPerformed(evt);
            }
        });
        txt_Telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_TelefonoKeyTyped(evt);
            }
        });

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));

        lbl_Usuario4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbl_Usuario4.setText("Telefono");

        javax.swing.GroupLayout Panel_FondoLayout = new javax.swing.GroupLayout(Panel_Fondo);
        Panel_Fondo.setLayout(Panel_FondoLayout);
        Panel_FondoLayout.setHorizontalGroup(
            Panel_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_FondoLayout.createSequentialGroup()
                .addGroup(Panel_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel_FondoLayout.createSequentialGroup()
                        .addGroup(Panel_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(Panel_FondoLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(Panel_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_Usuario)
                                    .addComponent(txt_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_Contraseña)
                                    .addComponent(txt_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_Contraseña1)
                                    .addComponent(txt_contraseñaRectificar, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_Atras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(114, 114, 114))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel_FondoLayout.createSequentialGroup()
                                .addComponent(lbl_INICIOS, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(Panel_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Usuario1)
                            .addComponent(txt_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Usuario2)
                            .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Usuario3)
                            .addComponent(txt_Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Usuario4)
                            .addComponent(txt_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        Panel_FondoLayout.setVerticalGroup(
            Panel_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_FondoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(Panel_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_FondoLayout.createSequentialGroup()
                        .addComponent(lbl_INICIOS)
                        .addGap(46, 46, 46)
                        .addComponent(lbl_Usuario)
                        .addGap(8, 8, 8)
                        .addComponent(txt_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_Contraseña)
                        .addGap(8, 8, 8)
                        .addComponent(txt_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_Contraseña1)
                        .addGap(8, 8, 8)
                        .addComponent(txt_contraseñaRectificar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_FondoLayout.createSequentialGroup()
                        .addComponent(lbl_Usuario1)
                        .addGap(8, 8, 8)
                        .addComponent(txt_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_Usuario2)
                        .addGap(8, 8, 8)
                        .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_Usuario3)
                        .addGap(8, 8, 8)
                        .addComponent(txt_Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_Usuario4)
                        .addGap(8, 8, 8)
                        .addComponent(txt_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Atras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pnl_FondoAb.add(Panel_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 780, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_FondoAb, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_FondoAb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_UsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_UsuarioMousePressed
        //txt_Usuario.enable(true);

    }//GEN-LAST:event_txt_UsuarioMousePressed

    private void txt_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_UsuarioActionPerformed

    private void txt_UsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_UsuarioKeyTyped

    }//GEN-LAST:event_txt_UsuarioKeyTyped

    private void txt_contraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_contraseñaMousePressed

    }//GEN-LAST:event_txt_contraseñaMousePressed

    private void txt_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contraseñaActionPerformed

    private void lbl_AtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_AtrasMouseEntered
        btn_Atras.setBackground(verde);
    }//GEN-LAST:event_lbl_AtrasMouseEntered

    private void lbl_AtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_AtrasMouseExited
        btn_Atras.setBackground(Color.lightGray);
    }//GEN-LAST:event_lbl_AtrasMouseExited

    private void lbl_AtrasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_AtrasMousePressed
        //llamar a la otra ventana
        //javax.swing.JOptionPane.showConfirmDialog(this, "INICIO: " + txt_Usuario.getText() + "\nContraseña: " + String.valueOf(txt_contraseña.getPassword()));
        Login log = new Login();
        log.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_lbl_AtrasMousePressed

    private void lbl_RegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_RegistrarMouseEntered
        btn_Registrar.setBackground(verde);
    }//GEN-LAST:event_lbl_RegistrarMouseEntered

    private void lbl_RegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_RegistrarMouseExited
        btn_Registrar.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_lbl_RegistrarMouseExited

    private void lbl_RegistrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_RegistrarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_RegistrarMousePressed

    private void Pnl_BarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pnl_BarraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_Pnl_BarraMouseDragged

    private void Pnl_BarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pnl_BarraMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_Pnl_BarraMousePressed

    private void txt_contraseñaRectificarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_contraseñaRectificarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contraseñaRectificarMousePressed

    private void txt_contraseñaRectificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contraseñaRectificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contraseñaRectificarActionPerformed

    private void txt_CorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_CorreoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CorreoMousePressed

    private void txt_CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CorreoActionPerformed

    private void txt_CorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CorreoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CorreoKeyTyped

    private void txt_NombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_NombreMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NombreMousePressed

    private void txt_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NombreActionPerformed

    private void txt_NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NombreKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NombreKeyTyped

    private void txt_ApellidosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ApellidosMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ApellidosMousePressed

    private void txt_ApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ApellidosActionPerformed

    private void txt_ApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ApellidosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ApellidosKeyTyped

    private void txt_TelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_TelefonoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TelefonoMousePressed

    private void txt_TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TelefonoActionPerformed

    private void txt_TelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TelefonoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TelefonoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Fondo;
    private javax.swing.JPanel Pnl_Barra;
    private javax.swing.JPanel btn_Atras;
    private javax.swing.JPanel btn_Registrar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lbl_Atras;
    private javax.swing.JLabel lbl_Contraseña;
    private javax.swing.JLabel lbl_Contraseña1;
    private javax.swing.JLabel lbl_INICIOS;
    private javax.swing.JLabel lbl_Registrar;
    private javax.swing.JLabel lbl_Usuario;
    private javax.swing.JLabel lbl_Usuario1;
    private javax.swing.JLabel lbl_Usuario2;
    private javax.swing.JLabel lbl_Usuario3;
    private javax.swing.JLabel lbl_Usuario4;
    private javax.swing.JPanel pnl_FondoAb;
    private javax.swing.JTextField txt_Apellidos;
    private javax.swing.JTextField txt_Correo;
    private javax.swing.JTextField txt_Nombre;
    private javax.swing.JTextField txt_Telefono;
    private javax.swing.JTextField txt_Usuario;
    private javax.swing.JPasswordField txt_contraseña;
    private javax.swing.JPasswordField txt_contraseñaRectificar;
    // End of variables declaration//GEN-END:variables
}
